### ISSUE TITLE
Request: Build and view watch later playlist in the site

### ISSUE THREAD

**Issue by rlh1994** [greggman/youtube_chromecast_speed_hack#6]
I find the youtube watch later playlist really useful, but unfortunately it is not possible to view the playlist directly outside of the youtube site.

It is however possible via some javascript to whilst on the watch later page (https://www.youtube.com/playlist?list=WL) get a list of all video IDs within the playlist, and then it is also possible to produce a url of video IDs that generates a temporary unlisted playlist that can be run through the existing site without issue. 

I have done much of the JS to produce the URL that makes that playlist, but have basically no experience with web development so there are a few things I don't know how to do:

1.  Open a new window/tab and run JS in that context once the loading has finished
2. Return a value from that window to the current page, and close that window
3. Open a new window with a url, wait until the URL for that window has a particular form and copy it, return it to the main tab and close the new one
4. Put this value into your site input field and submit.

The code I have so far that does all the playlist processing is below, but it's based off these two posts as I have never learnt JS proper (https://webapps.stackexchange.com/questions/72787/how-to-create-a-youtube-playlist-from-a-list-of-links https://gist.github.com/spyesx/27cecbe9483c507b9b098d942e98d62b )

```javascript
var videos = document.querySelectorAll('.yt-simple-endpoint.style-scope.ytd-playlist-video-renderer');
var r = [];
var json = [];
var pl_url = ''
var pl_url_true = ''

// Open watch later playlist (is there a way to force this to be a new tab?)
window.open('https://www.youtube.com/playlist?list=WL');

// TODO: Somehow run the following code on that page and return the value of pl_url

// Get each video in the list and add them to the array
r.forEach.call(videos, function(video) {
	var url = 'https://www.youtube.com' + video.getAttribute('href');
	url = url.split('&list=WL&index=');
	url = url[0];
    url = url.split('https://www.youtube.com/watch?v=');
	json.push(url[1]);
});

// Create the final URL that will need to be run
pl_url = 'http://www.youtube.com/watch_videos?video_ids='.concat(json.join())

// Open the new URL as a new window
window.open(pl_url);

// TODO: Somehow get the URL of this new window once it has loaded the page (or at least once it has the form https://www.youtube.com/watch?v=*list=* where * is wildcard)
pl_url_true = ''

// TODO: Set the value of the input field on the site equal to pl_url_true and execute 
```

**Comment by greggman** [comment]
The browser limits a bunch of things you can do. You can't read a youtube page from another page or from an iframe. In other words 

(1) Page A creates an iframe for youtube. Page A can not read or affect the contents of the iframe if it's in a different domain

(2) Page A creates another window/tab. Page A can not read or affect the content of the other window/tab if it's from a different domain

If you could then there would be all kinds of security issues with embedded iframes or pages that opened a new tab to other sites. So, at least the way above I don't think this is possible.

It is possible to use [the Youtube API](https://developers.google.com/youtube/v3) to [get a list of videos in a playlist](https://developers.google.com/youtube/v3/docs/playlistItems/list)

It [requires a google account and a project id](https://developers.google.com/youtube/v3/getting-started) and there are examples .

**Comment by rlh1994** [comment]
Thanks that makes sense. The issue with the API (which I haven't tried) seems to be that the watch later playlist still has no ID that can be accessed external to the domain. 

As a workaround I converted the above script to a bookmarklet that when run on the watch later playlist page, converts it to the unlisted playlist and allows the user to copy it to their clipboard for use in your site. Might not work exactly right depending on internet speeds as I just had to delay executions rather than knowing how to correctly check for a page load. This should at least mostly solve the problem for anyone looking to use your site with their watch later playlist.

```javascript
javascript:(function(){
	var videos = document.querySelectorAll('.yt-simple-endpoint.style-scope.ytd-playlist-video-renderer');
	var r = [];
	var json = [];
	var pl_url = '';
	var final_url = '';
	
	r.forEach.call(videos, function(video) {
		var url = 'https://www.youtube.com' + video.getAttribute('href');
		url = url.split('&list=WL&index=');
		url = url[0];
		url = url.split('https://www.youtube.com/watch?v=');
		json.push(url[1]);
	});
	
	pl_url = 'http://www.youtube.com/watch_videos?video_ids='.concat(json.join());
	
	var final_win = window.open(pl_url);
	setTimeout(() => {final_url = final_win.location.href; final_win.close();}, 1000);
	setTimeout(() => {prompt("Copy to clipboard: Ctrl+C, Enter", final_url);}, 3000);
	
	})();
```
